#!/bin/bash

basedir=$(readlink -m ${BASH_SOURCE[0]})
basedir=$(dirname ${basedir})

_error () {
	echo "${1}"
	exit 1
}

if [[ -f ${1} && ${1} == *.apk ]]; then
	java -jar ${basedir}/apksign.jar "${1}" || _error "apksign.jar failed!"
fi
