#!/bin/bash

version=1.6.0
reldate=2017/04/12

basedir=$(readlink -m "${BASH_SOURCE[0]}")
basedir=$(dirname "${basedir}")
rootdir="${PWD}"

_error () {
	echo "${1}"
	exit 1
}

_build () {

	if [[ -f ${1} && ${1} == *.apk ]]; then

		rm -rf "${rootdir}"/build-yokai

		xdelta=$(which xdelta3)
		if [[ ${xdelta} == "" ]]; then
			if [[ $(uname -m) == "x86_64" ]]; then
				xdelta="${basedir}"/patcher/xdelta3.64
			else	xdelta="${basedir}"/patcher/xdelta3.32
			fi
		fi

		source="${1}"
		sourceapk=$(basename "${source}")
		sourcedir=$(basename "${source}" .apk)

		apksign=${basedir}/apksign

		mkdir "${rootdir}"/build-yokai
		cp "${source}" ${rootdir}/build-yokai
		cd "${rootdir}"/build-yokai
		${apktool} d "${sourceapk}" || _error "apktool failed!"

		version=$(gawk '/^  versionName/{print $2}' < "${sourcedir}"/apktool.yml)

		if [[ -d "${basedir}"/delta/${patchdir}/${version} ]]; then
			patchdir="${basedir}"/delta/${patchdir}/${version}
		else
			echo -e "\n!! version ${version} is not supported !!\n"
			exit 1
		fi

		for arch in armeabi armeabi-v7a x86; do
			${xdelta} -d -f -s "${sourcedir}"/lib/${arch}/libSGF.so \
				"${patchdir}"/libSGF-${arch}.delta \
				libSGF-mod.so || _error "xdelta3 failed!"

			mv libSGF-mod.so "${sourcedir}"/lib/${arch}/libSGF.so
		done

		sed -e 's/const-string v3, "su"/const-string v3, "trololol"/g' \
			-i "${sourcedir}"/smali/com/example/sgf/MainActivity.smali || \
			_error "modifying sgf.MainActivity failed!"

		# only for US version
		if [[ ${patchdir} == *ywwus* ]]; then

			sed -e 's/bin\//nothinghere\//g' \
				-i "${sourcedir}"/smali/com/mparticle/internal/MPUtility.smali || \
				_error "modifying MPUtility failed!"

			sed -e 's/data\/local\//nothing\/here\//g' \
				-i "${sourcedir}"/smali/com/mparticle/internal/MPUtility.smali || \
				_error "modifying MPUtility failed!"

		fi

		sed -e 's/const-string v1, "sdk"/const-string v1, "leavemealone"/g' \
			-i "${sourcedir}"/smali/com/hangame/hsp/util/DeviceInfoUtil.smali ||
			_error "modifying hsp.util.DeviceInfoUtil failed!"

		${apktool} b "${sourcedir}" \
			-o Yokai-Watch-WW_${version}.apk || _error "apktool failed!"

		${apksign} Yokai-Watch-WW_${version}.apk || _error "apksign failed!"
		mv Yokai-Watch-WW_${version}.s.apk \
			"${rootdir}"/Yokai-Watch-WW_${version}.apk || _error "moving output file failed, ${rootdir} not writeable?"

		cd "${rootdir}"
		rm -rf "${rootdir}"/build-yokai

		echo -e "
Modified apk stored as

		${rootdir}/Yokai-Watch-WW_${version}.apk

copy to your device and install or issue

		adb install [-r] ${rootdir}/Yokai-Watch-WW_${version}.apk

if your device is connected to your computer.
"
	else	_error "file ${1} does not exist."
	fi

}

if ! which apktool ; then
	apktool="${basedir}"/patcher/apktool
else	apktool=$(which apktool)
fi

case ${1} in

	*us )	patchdir=com.level5.ywwwus
		_build "${1}"	;;

	*eu )	patchdir=com.level5.ywpeu
		_build "${1}"	;;

	* )	echo -e "Yokai Watch Wibble Wobble patcher

version ${version} (${reldate})

supported game versions
	US		EU
	1.1.1		1.0.2
	1.2.0
	1.2.1
	1.2.2
	2.0.0
	2.0.1
	2.0.2
	2.1.0
	2.1.1

usage:
	yokai-patcher	--us	<yokaiwatch.apk>
	yokai-patcher	--eu	<yokaiwatch.apk>

option:
	--help	[show this message]
"	;;

esac
