#!/bin/bash

version=1.2.0
reldate=2016/05/22

basedir=$(readlink -m "${BASH_SOURCE[0]}")
basedir=$(dirname ${basedir})
rootdir="${PWD}"

_error () {
	echo "${1}"
	exit 1
}

_build () {

	if [[ -f ${1} && ${1} == *.apk ]]; then

		rm -rf ${rootdir}/build-yokai

		which xdelta &>/dev/null || _error "xdelta not installed!"
		xdelta=$(which xdelta)

		source="${1}"
		sourceapk=$(basename "${source}")
		sourcedir=$(basename "${source}" .apk)

		apksign=${basedir}/apksign

		mkdir ${rootdir}/build-yokai
		cp "${source}" ${rootdir}/build-yokai
		cd ${rootdir}/build-yokai
		${apktool} ${apktoolparams} \
			d "${sourceapk}" || _error "apktool failed!"

		for arch in armeabi armeabi-v7a x86; do
			${xdelta} patch "${basedir}"/delta/com.level5.ywwwus/libSGF-${arch}.delta \
				"${sourcedir}"/lib/${arch}/libSGF.so libSGF-mod.so || _error "xdelta failed!"

			mv libSGF-mod.so "${sourcedir}"/lib/${arch}/libSGF.so
		done

		${apktool} ${apktoolparams} \
			b "${sourcedir}" \
			-o Yokai-Root.apk || _error "apktool failed!"

		cp -r "${sourcedir}/original/META-INF" .
		zip -r Yokai-Root.apk META-INF/ || _error "zip failed!"

		${apksign} Yokai-Root.apk || _error "apksign failed!"
		mv Yokai-Root.s.apk Yokai-Root.apk

		echo -e "
Modified apk stored as

		${rootdir}/build-yokai/Yokai-Root.apk

copy to your device and install or issue

		adb install [-r] ${rootdir}/build-yokai/Yokai-Root.apk

if your device is connected to your computer.
"
	else	_error "file ${1} does not exist."
	fi

}

case ${1} in

	*alt )	apktool=${basedir}/apktool
		apktoolparams="-p ${basedir}/framework"
		_build "${2}"	;;

	*alt2 )	apktool=${basedir}/apktool
		apktoolparams=""
		_build "${2}"	;;

	*.apk )	which apktool &>/dev/null || _error "apktool not installed!"
		apktool=$(which apktool)
		apktoolparams=""
		_build "${1}"	;;

	* )	echo -e "Yokai Watch Wibble Wobble (US) root patcher

version ${version} (${reldate})
usage:
	yokai-patcher		<yokaiwatch.apk>
	yokai-patcher	--alt	<yokaiwatch.apk>
	yokai-patcher	--alt2	<yokaiwatch.apk>

option:
	--alt	[use supplied apktool with supplied framework]
	--alt2	[use supplied apktool with default framework]
	--help	[show this message]
"	;;

esac
